// Generated by https://quicktype.io

namespace autopi.net.core.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MostRecentPositionResponse
    {
        [JsonProperty("cog")]
        public double Cog { get; set; }

        [JsonProperty("alt")]
        public double Alt { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("sog")]
        public double Sog { get; set; }

        [JsonProperty("utc")]
        public DateTimeOffset Utc { get; set; }

        [JsonProperty("altitude")]
        public double Altitude { get; set; }

        [JsonProperty("ts")]
        public DateTimeOffset Ts { get; set; }

        [JsonProperty("nsat")]
        public long Nsat { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

}
